
[core]
#=====单位信息====#
name:测试
tags:载具
displayDescription:"""
\测试用
"""
class:CustomUnitMetadata
maxHp:1000
mass:12500
radius:27
#====核心资源====#
maxShield:10
price:10
shieldRegen:0.025
startShieldAtZero:true
energyMax:10
energyRegen:0.05
energyStartingPercentage:0
energyNeedsToRechargeToFull:true
#====运输机制====#
#离开x轴:7
exit_y:35
#离开旋转角度:90
exit_moveAwayAmount:20
#====核心机制====#
canNotBeDamaged:true
showInEditor:true
#==========================Image=========================#

[graphics]
total_frames:1
image:SHARED:blank.png
imageScale:0.6
image_turret:SHARED:blank.png
scaleTurretImagesTo:0.6
image_shadow:AUTO
shadowOffsetX:3
shadowOffsetY:-3
dustEffect:true
#==========================attack=========================#

[attack]
canAttack:true
canAttackFlyingUnits:false
canAttackLandUnits:true
canAttackUnderwaterUnits:false
turretMultiTargeting:true
maxAttackRange:437
shootDelay:437


[movement]
#=坦克类单位的航速为1.**=#
#=汽车类单位的航速为2.**=#
movementType:LAND
moveSpeed:1
moveAccelerationSpeed:0.0025
moveDecelerationSpeed:0.025
turnAcceleration:0.058
moveSlidingMode:false
moveIgnoringBody:false
reverseSpeedPercentage:0.5
#加入队形:true

[action_停车]
pos:10
text:[停 车]
displayType:infoOnly
clearActiveWaypoint:true
alwaysSinglePress:true
canPlayerCancel:false
allowMultipleInQueue:false
buildSpeed:0s

[ai]
useAsAttacker:true
useAsTransport:false


#只需要加上imageStack就可以了，使用,隔开，从底部开始
[decal_mig]
#imageStack:tanke3_01.png,tanke3_02.png,tanke3_03.png,tanke3_04.png,tanke3_05.png,tanke3_06.png,tanke3_07.png,tanke3_08.png,tanke3_09.png,tanke3_10.png,tanke3_11.png,tanke3_12.png,tanke3_13.png

imageStack:tanke3_13.png,tanke3_12.png,tanke3_11.png,tanke3_10.png,tanke3_09.png,tanke3_08.png,tanke3_07.png,tanke3_06.png,tanke3_05.png,tanke3_04.png,tanke3_03.png,tanke3_02.png,tanke3_01.png
#stack_indexStart:0

#stack_hOffset:0
#stack_frameOffset:4

#stack_indexCount:13
#frame_width:26
#frame_height:35

#hOffset:1